# -*- coding: utf-8 -*-
{
    "name": "Hospital Management System",
    "version": "1.0.6",
    "currency": 'UGX',
    "sequence": '10',

    'summary': """
        Basic Hospital Management - Base Healthcare Management System App
        .""",

    'description': """
        This Hospital management app has healthcare management system features like 
        hospital management, patient management, staff management, appointment management, 
        treatment , evaluation management, medical prescription, procedures, pharmacy management 
        and hospital canteen management
    """,

    'author': "Techthings",
    'website': "https://www.techthings.it",
    'category': 'Health',
    'version': '0.1',
    'depends': ['base', "sale_management", "stock", "account", 'mail', 'board', 'website'],
    'data': [
        # 'security/ir.model.access.csv',
        'security/hospital_groups.xml',
        'data/ir_sequence_data.xml',
        'views/assets.xml',
        'views/login_page.xml',
        'views/main_menu_file.xml',
        'wizard/appointments_invoice_wizard.xml',
        'wizard/create_prescription_invoice_wizard.xml',
        'wizard/create_prescription_shipment_wizard.xml',
        'views/medicament.xml',
        'views/drug_route.xml',
        'wizard/lab_test_create_wizard.xml',
        'wizard/lab_test_invoice_wizard.xml',
        'views/prescription_order.xml',
        'views/directions.xml',
        'views/dose_unit.xml',
        'views/patient_evaluation.xml',
        'views/family_disease.xml',
        'views/inpatient_registration.xml',
        'views/inpatient_medication.xml',
        'views/insurance_plan.xml',
        'views/appointment.xml',
        'views/insurance.xml',
        'views/patient_lab_test.xml',
        'views/lab_test_units.xml',
        'views/lab.xml',
        'views/neomatal_apgar.xml',
        'views/pathology_category.xml',
        'views/pathology_group.xml',
        'views/pathology.xml',
        'views/patient_disease.xml',
        'views/patient_medication.xml',
        'views/patient_medication1.xml',
        'views/patient_pregnancy.xml',
        'views/patient_prenatal_evaluation.xml',
        'views/patient.xml',
        'views/physician.xml',
        'views/prenatal.xml',
        'views/prescription_line.xml',
        'views/puerperium_monitor.xml',
        'views/rcri.xml',
        'views/rounding_procedure.xml',
        'views/test_criteria.xml',
        'views/test_type.xml',
        'views/vaccination.xml',
        'views/res_partner.xml',
        'wizard/lab_test_create_wizard.xml',
        'wizard/lab_test_invoice_wizard.xml',
        'report/report_view.xml',
        'report/appointment_receipts_report_template.xml',
        'report/view_report_document_lab.xml',
        'report/view_report_lab_result_demo_report.xml',
        'report/newborn_card_report.xml',
        'report/patient_card_report.xml',
        'report/patient_diseases_document_report.xml',
        'report/patient_medications_document_report.xml',
        'report/patient_vaccinations_document_report.xml',
        'report/prescription_demo_report.xml',

    ],
    'demo': [],
    'application': True,
    'installable': True
}
